[env]
TERM = "xterm-256color"

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.7
blur = true
decorations = "Buttonless"
startup_mode = "Fullscreen"
option_as_alt = "Both"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 20.0

[colors]
# Catppuccin Mocha 配色（與本地 tmux 一致）
[colors.primary]
background = '#1e1e2e'
foreground = '#cdd6f4'

[colors.selection]
text = '#2e3440'
background = '#88c0d0'

[terminal]
osc52 = "CopyPaste"  # 允許終端機存取剪貼簿

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "H", mods = "Alt", chars = "\u001bh" },
  { key = "J", mods = "Alt", chars = "\u001bj" },
  { key = "K", mods = "Alt", chars = "\u001bk" },
  { key = "L", mods = "Alt", chars = "\u001bl" },
]

[general]
import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]
