[env]
TERM = "xterm-256color"

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.8
blur = true
decorations = "Buttonless"
startup_mode = "Fullscreen"
option_as_alt = "Both"

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 20.0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[general]
import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]
