general {
    lock_cmd = pidof hyprlock || hyprlock       # 避免重複執行鎖定指令
    before_sleep_cmd = loginctl lock-session    # 在系統休眠前鎖定螢幕
    after_sleep_cmd = hyprctl dispatch dpms on  # 系統喚醒後打開螢幕
}

listener {
    timeout = 300                                # 5 分鐘閒置
    on-timeout = loginctl lock-session           # 鎖定螢幕
}

listener {
    timeout = 330                                # 5.5 分鐘閒置
    on-timeout = hyprctl dispatch dpms off       # 關閉螢幕電源 (主機不休眠)
    on-resume = hyprctl dispatch dpms on         # 喚醒時恢復螢幕
}
